
package ru.rob.integration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseStatusType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResponseStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NotSent"/&gt;
 *     &lt;enumeration value="Sent"/&gt;
 *     &lt;enumeration value="AutoGenerated"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "ResponseStatusType")
@XmlEnum
public enum ResponseStatusType {

    @XmlEnumValue("NotSent")
    NOT_SENT("NotSent"),
    @XmlEnumValue("Sent")
    SENT("Sent"),
    @XmlEnumValue("AutoGenerated")
    AUTO_GENERATED("AutoGenerated");
    private final String value;

    ResponseStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResponseStatusType fromValue(String v) {
        for (ResponseStatusType c: ResponseStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
